module.exports = {
    tags: ["demo"],
    "Propel demo test" : function (browser) {
         browser 
         .maximizeWindow()
         .url("https://hhf.qa.howapp.co.uk/login") // Go to a url
         .waitForElementVisible('body', 1000) // wait till page loads
         .assert.title("Propel Admin ▪ Propel Finance ▪ Personal. Progressive. Partnering.") // Make sure Site title matches
         .assert.visible("input[type=email]") 
         .setValue("input[type=email]", "AAshok@propelfinance.co.uk") // send values
         .assert.visible("input[type=password]")
         .setValue("input[type=password]", "Saisantoo56")
         .saveScreenshot('C://Users//ashok//OneDrive//Documents//Propel-Nightwatch//tests_output//reportsScreenshots//homepage.png')
         .click('button[type=submit]') // click on search box
         .click("#createMenuLink > svg > path") 
         .click("#secondary-sidebar-create > div.secondary-sidebar-content.text-left.mt-20 > div:nth-child(1) > a > div.menu-item-text")
         .click("#app > main > div > div.deal-type-wrapper > div:nth-child(2) > div.col-md-4.offset-md-1 > button")
         .execute('window.scrollTo(0,document.body.scrollHeight);') // Participants Page starts here
         .click("body > span > span > span.select2-search.select2-search--dropdown > input")
         .pause(2000) 
         .click("#participants_form > div.form-group.vendor > div > div > span > span.selection > span")
         .setValue("body > span > span > span.select2-search.select2-search--dropdown > input","Gav's Plan shop")
         .waitForElementPresent(".select2-results__option--highlighted", 30000)             
         .click(".select2-results__option--highlighted") 
         .setValue("#account-manager","Clare Montgomey") 
         .waitForElementPresent("#select2-sales-person-container", 30000) 
         .click("#select2-sales-person-container") 
         .pause(2000)
         .click(".select2-results__options>li:nth-of-type(2)")
         .pause(2000)
         .click("#select2-sales-admin-person-container")
         .pause(2000)
         .click("#select2-sales-admin-person-results>li:nth-of-type(1)")
         .pause(2000)
         .click("#btnSaveIndirectContinue")  //customer page starts here       
         .pause(5000)
         .click("#app > main > div > div.business-type-wrapper > div:nth-child(2) > div > div > div > select")               
         .click('select.business-type option[data-slug="limited-company"]')
         .pause(10000)        
         .setValue("#name", "Propel (uk) Limited")
         .pause(2000)
         .setValue("#company-registration-number","06090856")
         .click("#customers_form > div:nth-child(8) > div > button")
         .pause(10000)
         .click("li:nth-child(1) .mb-0:nth-child(1)")
         .pause(2000)
         .setValue("#customer_details_trading_name","test") 
         .pause(3000)         
         //.waitForElementVisible('#select2-nature_of_business-container',30000)
         .execute('window.scrollTo(0,document.body.scrollHeight);')
         //body > span > span > span.select2-search.select2-search--dropdown > input
         .click("#select2-nature_of_business-container")
         .pause(2000)                
         .setValue(".select2-search--dropdown > .select2-search__field","Acc")
         .pause(2000) 
         .click(".nature-of-business-select .select2-results__option--highlighted")
         //.pause(2000)
         .setValue("#customer_details_bank_sort_code","121016")
         .pause(2000)
         .setValue("#customer_details_bank_account_number","12101656")
         .pause(2000)
         .click("#btnSaveContinue > span")
         .pause(2000)
         .click("#btnSaveContinue")
         .pause(2000)
         .click("#app > main > div > div.cloned-template.mb-20 > div > div > div.col-md-12.edit-wrapper > div:nth-child(7) > div:nth-child(1) > div > div > label")
         //.click("#app > main > div > div.individual-list-wrapper.mb-20 > div > div > div.col-md-12.read-only-wrapper > div:nth-child(5) > div:nth-child(1) > div > div > label")
         .click(".row:nth-child(1) > .col-md-12 > .col-md-12:nth-child(21) .col-3:nth-child(1) .custom-control-labe")
         .pause(2000)
         .click(".row:nth-child(1) > .col-md-12 > .col-md-12 .col-4 .col-4:nth-child(1) .custom-control-label")
         .pause(3000)
         .click(".row:nth-child(1) > .col-md-12 > .col-md-12 #title")
         .pause(2000)
         .click(".row:nth-child(1) > .col-md-12 > .col-md-12 #title > option:nth-child(5)")
         .pause(3000)
         .setValue("#app > main > div > div.cloned-template.mb-20 > div > div > div.col-md-12.edit-wrapper > div:nth-child(11) > div > input","Ashok")
         .pause(2000)
         .setValue("#app > main > div > div.cloned-template.mb-20 > div > div > div.col-md-12.edit-wrapper > div:nth-child(12) > div > input","kumar")
         .pause(2000)
         .setValue("#app > main > div > div.cloned-template.mb-20 > div > div > div.col-md-12.edit-wrapper > div.row.form-group.mt-8 > div > input.form-control.md-form-control.col-3.float-left.mr-3.dob.number-only","11")
         .setValue("#app > main > div > div.cloned-template.mb-20 > div > div > div.col-md-12.edit-wrapper > div.row.form-group.mt-8 > div > input.form-control.md-form-control.col-3.float-left.mr-3.number-only.px-2","11")
         .setValue("#app > main > div > div.cloned-template.mb-20 > div > div > div.col-md-12.edit-wrapper > div.row.form-group.mt-8 > div > input:nth-child(5)","1982")
         .pause(3000)
         .setValue(".form-control md-form-control","s@gmail.com")
         //.setValue("#app > main > div > div.individual-list-wrapper.mb-20 > div > div > div.col-md-12.edit-wrapper > div.form-group.mt-8.email-wrapper > div:nth-child(1) > input","ashok@gmail.com")
         .pause(2000)
         .setValue("#app > main > div > div.individual-list-wrapper.mb-20 > div > div > div.col-md-12.edit-wrapper > div.postcode-search-context-wrapper > div:nth-child(3) > div > input","BS1 6DD")
         .pause(2000)
         .click("#app > main > div > div.cloned-template.mb-20 > div > div > div.col-md-12.edit-wrapper > div.postcode-search-context-wrapper > div:nth-child(4) > div > button")
         .pause(5000)
         .click("#app > main > div > div.cloned-template.mb-20 > div > div > div.col-md-12.edit-wrapper > div.form-group.mt-9 > div > button.btn.btn-primary.btn-sm.btn-loader.btn-add-individual")
         .pause(3000)
         .click("#btnSaveContinue > span")
         .pause(3000)
         .click("#app > main > div > div.equipment-delivery-address-wrapper > div:nth-child(2) > div:nth-child(1) > div > label")
         .pause(3000)
         .click("#app > main > div > div.equipment-delivery-address-wrapper > div.proceed-btn-wrapper > div > div > div > button")
         .pause(3000)
         .click("#btnSaveContinue > span")
         //.waitForElementVisible("category", 2000)
         .click("#type > option:nth-child(2)")
         .click("#category > option:nth-child(2)")
         .setValue("#description","IT Equipment")
         .click("#condition > option:nth-child(2)")
         .setValue("#quantity","1000")
         .setValue("#value","5000")
         .click("#app > main > div > div.step4.cloned-template.mt-9.mb-20 > table > tbody > tr.edit-wrapper > td > div.row.mt-9 > div > button.btn.btn-primary.btn-sm.btn-loader.btn-add-equipment")
         .pause(5000)
         .click("#btnSaveContinue")
         .waitForElementVisible("#product > option:nth-child(2)",3000)
         .click("#product > option:nth-child(2)")
         .click("#btnSaveContinue")
         .click("#rate_card > option:nth-child(2)")
         .click("#vue-components > div.non-hp-details-wrapper > div.settlement-wrapper.mt-9 > div:nth-child(3) > div > button")
         .pause(5000)
         .setValue("#finance_company","PBS")
         .setValue("#agreement_number","123456")
         .setValue("#value","200")
         //.click("#frequency > option:nth-child(2)")
         .click("#create_settlement_form > div.modal-footer > button.btn.btn-primary.btn-sm.btn-loader")
         //.waitForElementVisible("#btnCalculateProposal",5000)
         .click("#frequency > option:nth-child(2)")
         .click("#term > option:nth-child(2)")
         .pause(3000)
         .execute('window.scrollTo(0,document.body.scrollHeight);')         
         .click("#btnCalculateProposal")
         .pause(5000)
         //.execute('window.scrollTo(0,document.body.scrollHeight);')
         .click("#btnSaveContinue > span")
         .pause(2000)
         .click("#app > main > div.footer-nav-fixed.with-secondary-sidebar > button > span")
         .pause(2000)
         .click("#firstSubmissionModal > div > div > div.modal-body > div.form-group.mt-8 > div > div > label")
         .pause(2000)
         .click("#firstSubmissionModal > div > div > div.modal-footer > button.btn.btn-primary.btnConfirmFirstSubmission")
         .pause(10000)
         .saveScreenshot('C://Users//ashok//OneDrive//Documents//Propel-Nightwatch//tests_output//reportsScreenshots//submit-proposal.png')
         .end();
       }
 };